language: php

sudo: true

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

addons:
  hosts:
    - system.hyn.me
    - tenant.hyn.me

install:
  # fix ipv6 issue that prevented composer requests and resulted in failing builds
  - sudo sh -c "echo 'precedence ::ffff:0:0/96  100' >> /etc/gai.conf"
  # updates composer on travis
  - travis_retry composer self-update
  # clear composer cache, might speed up finding new tags
  - travis_retry composer clear-cache
  # set the global github token, so connections won't be cancelled
  - composer config -g github-oauth.github.com $GITHUB_TOKEN
  # create a new database for the hyn connection
  - mysql -e 'create database hyn;' -uroot
  - mysql -e "grant all privileges on *.* to 'travis'@'localhost' with grant option;" -uroot
  # create a new laravel project in the subfolder laravel (default composer behaviour)
  - composer create-project laravel/laravel
  # set global variables
  - export DB_USERNAME=travis DB_DATABASE=hyn DB_PASSWORD=

script:
  # run the script calling unit tests and so on
  - ./scripts/travis.sh